* Pyphlogiston

A simple, experimental python/sqlite3/fossile storage solution for document-style JSON data records.

Emphasis is on:
- Pytest to build it up nicely, if not completely.
- Latest python features. Backward compatibility not considered.

* Setup Steps:
** 0. Installation
*** Toolchain level
   Not going to start here. The code for Fossil has been compiled, with attention to JSON API 
*** System prep
    sudo adduser       fossil
    sudo mkdir        /home/fossil/{bin,museum}
    cd                /home/fossil/bin
    ln          -s    /home/osboxes/src/fossil-snapshot-20210429/fossil
    sudo /home/osboxes/src/fossil-snapshot-20210429/fossil init /home/fossil/museum/museum.fossil
    sudo chown  -Rv    fossil:fossil /home/fossil


    project-id: 422d1937ecb9aab06e40d1a27781e29aeb72fc4c
    server-id:  8a1cce0be8699e9de9d63565354806c96bd8c400
    admin-user: root (initial password is "zMxVg5SB2E")

*** Service installation 
#+name: setup_fossil_service
#+begin_src sh
  FOSSIL=/home/fossil/bin/
  TCPPORT=9000
  USER_SERVICE=/home/osboxes/.config/systemd/user
  USER_MUSEUM=/home/fossil/museum
  mkdir -p ${USER_MUSEUM}
  mkdir -p ${USER_SERVICE}
  FOSSIL_ARGS="--create --localauth --localhost --jsmode inline --nojail --nossl --port ${TCPPORT} ${USER_MUSEUM}/museum.fossil"
  cat <<EOF>${USER_SERVICE}/fossil.service
  [Unit]
  Description=Fossil user server
  After=network.target

  [Service]
  WorkingDirectory=${USER_MUSEUM}
  ExecStart=${FOSSIL}fossil server ${FOSSIL_ARGS}
  Restart=always
  RestartSec=3

  [Install]
  WantedBy=sockets.target
  WantedBy=multi-user.target 
  EOF
  chmod +x ${USER_SERVICE}/fossil.service
  systemctl --user daemon-reload
  systemctl --user enable    fossil.service
  systemctl --user start     fossil.service
  systemctl --user status -l fossil.service 
#+end_src



journalctl --output=verbose --user-unit=fossil.service

** 1. Startup
   How we make sure the Fossil service is running
** 2. Create
   Add records
** 3. Review
*** 3.0 Single entry history
*** 3.1 Category history
** 4. Update
*** 4.0 Change a record
*** 4.1 Merge records
*** 4.2 Split record

* Example Usage

** The 'schema' is captured two Enums and a dict
There are a variety of data type in AWS, and we'd like to study their relationships.

We need to define two enumerations as arguments

class PType(IntEnum):
    '''Each PType will become:
    - a (prefixed) table in a SQLite3 database
    - a directory in a staging filesystem tree
    '''

class DType(IntEnum):
    '''The types of data rows in the PType tables.
    '''

dtype2table = {
    DType.entry0.value : 'table0',
    DType.entry1.value : 'tableX',
    ...
    }

** Worked example
AWS botocore service files have (at least) four PType entries. What we really care 
about are the operations (methods) and their argument/return types (shapes)

class PType(IntEnum):
    metadata = 0
    operations = 1
    shapes = 2
    documentation = 3

class DType(IntEnum):
